# Data Cleaning Appendix

Here is the importation, cleaning, and re-exportation of data for INFO 2950.

In [9]:
## load libraries

## our old friends...
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
# load CSVs

agriculture=pd.read_csv('agriculture.csv', na_values={'false','False','FALSE'})
energy=pd.read_csv('energy.csv',  na_values={'false','False','FALSE'})
waste=pd.read_csv('waste.csv',   na_values={'false','False','FALSE'})
industrial=pd.read_csv('industrial-processes.csv',  na_values={'false','False','FALSE'})
bunker_fuels=pd.read_csv('bunker-fuels.csv',  na_values={'false','False','FALSE'})

## load HDI data
hdi = pd.read_csv('Human Development Index (HDI)-2.csv', header = 5)
cols = {'Country', '2019'} # subset to just keep 2019 hdis
hdi = hdi[cols] # keeping only relevant data

hdi['Country'] = hdi['Country'].str.strip(' ')

hdi = hdi.rename(columns={'Country': 'country', '2019': 'hdi'})

hdi.to_csv("hdi.csv")
# sorting and re-formatting

agriculture = agriculture.sort_values('Country/Region')
energy = energy.sort_values('Country/Region')
waste = waste.sort_values('Country/Region')
industrial = industrial.sort_values('Country/Region')
bunker_fuels = bunker_fuels.sort_values('Country/Region')

ag_ghgchange = (agriculture['2018']-agriculture['2008'])
energy_ghgchange = (energy['2018']-energy['2008'])
waste_ghgchange = (waste['2018']-waste['2008'])
industrial_ghgchange = (industrial['2008']-industrial['1998'])
bunker_ghgchange = (bunker_fuels['2008']-bunker_fuels['1998'])

# merging

data_ghgchange = {'country': agriculture['Country/Region'].str.strip(' '), 'agriculture': ag_ghgchange, 'energy': energy_ghgchange,
                  'waste': waste_ghgchange, 'industrial': industrial_ghgchange, 'bunker fuels': bunker_ghgchange}
# data_ghgchange = {'country': agriculture['Country/Region'].str.strip(' '), 'agriculture': agriculture['2018'], 'energy': energy['2018'],
#                   'waste': waste['2018'], 'industrial': industrial['2018'], 'bunker fuels': bunker_fuels['2018']}
df_ghgchange = pd.DataFrame.from_dict(data_ghgchange, orient = 'index')
df_ghgchange = df_ghgchange.transpose()

df_ghgchange

         country agriculture  energy waste industrial bunker fuels
57   Afghanistan       67.42   -4.08  -0.8       0.54         -1.3
145      Albania        2.17    0.68  0.95       0.05        -0.03
38       Algeria       58.44  -17.34 -0.39       5.61         0.56
177      Andorra       -0.05    0.15  0.08          0            0
47        Angola         1.2    64.3 -2.18       1.13         1.59
..           ...         ...     ...   ...        ...          ...
29     Venezuela       -67.4   44.14  0.62       6.66         1.41
23       Vietnam      126.44  126.77  1.21       3.64        -0.78
122        Yemen       -11.3     4.3  0.34       0.22        -0.03
59        Zambia       27.67   -5.72  0.52       0.89         0.63
49      Zimbabwe       83.42    4.39  0.78       2.39         1.06

[195 rows x 6 columns]

Let's export this dataframe for use in the project:

In [11]:
df_ghgchange.to_csv("df_ghgchange.csv")

In [12]:
# load CSV

industry_data=pd.read_csv('CIA_industry_data.csv')

# column renaming

industry_data=industry_data.rename(columns={'Country/Region': 'country'})

# dropping irrelevant columns
industry_data=industry_data.drop(columns='Jute')

# merging with HDI data

analysis_two=hdi.merge(industry_data, how='left', on='country')

# finding hdi values that could not be turned to strings

analysis_two[analysis_two.hdi.str.find('..')==0]

# dropping these columns

analysis_two=analysis_two.drop([189,195])

# converting to float

analysis_two.hdi=analysis_two.hdi.astype(float)

# exporting

analysis_two.to_csv("analysis_two.csv")